default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: seat_user
  password: 'seat_user'

development:
  <<: *default
  database: seat_development_db

test:
  <<: *default
  database: seat_test_db

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: seat_production_db